name: "Webhook Event Example"

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  respond-to-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log Event Name
        run: echo "Event of type:" ${{ github.event.action }}

      - name: Log Full Event Payload
        run: echo "${{ toJson(github.event) }}"
